# Definindo o Nome do workflow
name: Test WorkFlow

# Definindo quando o workflow sera disparado
on:
  push:
    branches: [main, developer ]
       
# Definindo os jobs que o workflow executará
jobs:
  test_job:
    name: Executando o Job de Teste
    runs-on: self-hosted

    steps:
     - name: Step 1
       uses: actions/checkout@v2

     - name: Step 2
       run: echo "Ola mundo"

     - name: Step 3
       run: echo "este é o passo 3"

     - name: Step 4
       run: echo "este é o passo 4"
          
   

     
